//API action types
export const POST_ACCOUNT_LOGIN_SUCCESS = "POST_ACCOUNT_LOGIN_SUCCESS";
export const POST_ACCOUNT_LOGIN_FAIL = "POST_ACCOUNT_LOGIN_FAIL";

export const POST_ACCOUNT_JOIN_SUCCESS = "POST_ACCOUNT_JOIN_SUCCESS";
export const POST_ACCOUNT_JOIN_FAIL = "POST_ACCOUNT_JOIN_FAIL";
