//API action types
export const POST_MY_PATENT_LIST_SUCCESS = "POST_MY_PATENT_LIST_SUCCESS";
export const POST_MY_PATENT_LIST_FAIL = "POST_MY_PATENT_LIST_FAIL";

export const POST_PATENT_APPLY_SUCCESS = "POST_PATENT_APPLY_SUCCESS";
export const POST_PATENT_APPLY_FAIL = "POST_PATENT_APPLY_FAIL";

export const SET_APPLY_FG = "SET_APPLY_FG";
