//API action types
export const OPEN_PATENT_MODAL = "OPEN_PATENT_MODAL";
export const CLOSE_PATENT_MODAL = "CLOSE_PATENT_MODAL";

export const OPEN_PATENT_FINISH_MODAL = "OPEN_PATENT_FINISH_MODAL";
export const CLOSE_PATENT_FINISH_MODAL = "CLOSE_PATENT_FINISH_MODAL";

export const OPEN_PAYMENT_MODAL = "OPEN_PAYMENT_MODAL";
export const CLOSE_PAYMENT_MODAL = "CLOSE_PAYMENT_MODAL";

export const OPEN_ALERT_MODAL = "OPEN_ALERT_MODAL";
export const CLOSE_ALERT_MODAL = "CLOSE_ALERT_MODAL";
